version: '3'
services:
  squares-api:
    image: squares.api
    build:
      context: .
      dockerfile: Squares.API/Dockerfile
    ports:
      - '8000:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - ./Users/ajeetraina/data/redisinsight:/db 